[package]
name = "imageRotationIssue"
version = "0.1.0"
authors = ["d7p"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
photon-rs = "0.2.0"

